# Site settings
title: Andy Barron
email: AndrewLBarron@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Awesome description
  goes
  here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://andybarron.github.io" # the base hostname & protocol for your site
# twitter_username: AndyLBarron
github_username:  AndyBarron
linkedin_username: AndyLouisBarron

# pretty urls
permalink: pretty

# Build settings
markdown: kramdown
